#!/usr/bin/env bash

set -e

function parse_ostype {
    case "$OSTYPE" in
        solaris*) echo "solaris" ;;
        darwin*)  echo "osx" ;;
        linux*)   echo "linux" ;;
        bsd*)     echo "bsd" ;;
        *)        echo "unknown" ;;
    esac
}

host=(${HOSTNAME//./ })
platform=$(parse_ostype)

CONFIG_DIR="dotbot_configs"
CONFIG="${CONFIG_DIR}/install_${host[0]}_${platform}.conf.yaml"
DOTBOT_DIR="dotbot"

echo "Using config: ${CONFIG}"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
