#!/usr/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

/usr/lib/geoclue-2.0/demos/agent &
redshift-gtk &
espada &

exec i3
