[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 0

[package]
disabled = true

[rust]
disabled = true

[custom]

[custom.tab]
command = "tab --starship"
when = "tab --starship"
style = "bold blue"
symbol = "in "
